ArdeleanuStefan_Task2
maxlig79/accademy pull request #14
Opened 2022-01-18 17:27 UTC by ArdeleanuStefan

2022-01-20 09:08 UTC, maxlig79 requested changes

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +    dynamicArray = nullptr;
Please use initializer list (in general better performance)

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +    {
I don't think this is needed, if you remove the if statement should work.

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +        return ok;
Multiple return should be avoided

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +    dynamicArray = new std::string[obj.get_size()];
Look like a memory leak

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +    return *this;
Please avoid multiple return

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +        dynamicArray = nullptr;
I don't think this is needed

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/DynamicStringArray.cpp
> +        dynamicArray = nullptr;
Not needed

2022-01-20 09:08 UTC, maxlig79 commented on ArdeleanuStefan_Task2/src/Test.cpp
> +    obj1.deleteEntry("doi");
You should check also the return value of the deleteEntry

2022-01-21 10:27 UTC, maxlig79 approved these changes

2022-01-21 10:37 UTC, vlcristi91 approved these changes

2022-01-21 10:37 UTC, merged