Vlad task2
maxlig79/accademy pull request #15
Opened 2022-01-20 09:05 UTC by vlad-iancu

2022-01-20 15:07 UTC, maxlig79 requested changes

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    m_dynamicArray = new std::string[_size];
Please use intializer list (in general better performance)

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +        return *this;
Please avoid multiple return in methods

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    delete[] m_dynamicArray;
This will not work for self assignment

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    return m_dynamicArray[index];
You don't need this because you have getEntry

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +{
Not needed

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +void DynamicArray::deleteEntry(const std::string &entry)
The deleteEntry should return a bool that is true if the element was found and removed.

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    std::string *out = new std::string[m_size];
If the entry is in the array you have allocated one extra string

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    m_size = newSize;
If the entry is in the array you will have a wrong size for the array.

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    return m_dynamicArray[index];
What happen if the index is not in range?

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/include/DynamicArray.hpp
> +    DynamicArray(DynamicArray &&source);
If you have implemented this you should use it

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/include/DynamicArray.hpp
> +    DynamicArray &operator=(DynamicArray &&source);
If you have implemented this you should use it

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/SConscript
> +from subprocess import check_output
For this task I can't see the benefits of having booth a test and a main,
I suggest you to use only the test(with boost test framework).

2022-01-20 15:07 UTC, maxlig79 commented on vlad_task2/src/DynamicArray.cpp
> +    reallocate(m_size + 1);
Do you need a parameter for this function? Can it be reallocate()?

2022-01-21 10:45 UTC, nbiro commented on vlad_task2/src/DynamicArray.cpp
> +    m_size = newSize;
m_size is always 0 after this function is called...

2022-01-21 15:22 UTC, maxlig79 approved these changes

2022-01-21 15:33 UTC, ArdeleanuStefan approved these changes

2022-01-21 15:39 UTC, merged