Add dynamic string array
maxlig79/accademy pull request #16
Opened 2022-01-21 11:59 UTC by silvanadomnica

2022-01-21 14:33 UTC, maxlig79 requested changes

2022-01-21 14:33 UTC, maxlig79 commented on silvanadomnica_Task2/DynamicStringArray.cpp
> +            return true;
Please avoid multiple return.

2022-01-21 14:33 UTC, maxlig79 commented on silvanadomnica_Task2/DynamicStringArray.cpp
> +        dynamicArray=new string[size];
What happen if the dynamicArray is already allocated?

2022-01-21 14:33 UTC, maxlig79 commented on silvanadomnica_Task2/DynamicStringArray.cpp
> +{
As a suggestion use initializer list, in general you have better performance.

2022-01-25 12:23 UTC, maxlig79 requested changes

2022-01-25 12:23 UTC, maxlig79 commented on silvanadomnica_Task2/DynamicStringArray.cpp
> +        return nullptr;
nullptr is not a string.

2022-01-26 10:04 UTC, maxlig79 approved these changes

2022-01-26 10:06 UTC, nbiro approved these changes

2022-01-26 10:06 UTC, merged