Herciuana task2
maxlig79/accademy pull request #19
Opened 2022-01-25 18:34 UTC by herciuana

2022-01-26 07:17 UTC, maxlig79 requested changes

2022-01-26 07:17 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +        return nullptr;
nullptr is not a string

2022-01-26 07:17 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +    if (this->size != 0)
This will not work for self assignment.

2022-01-26 07:17 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +    else
This mean that if the string is not found the function will not return anything?

2022-01-26 07:17 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +{
Please use initialize list, in general you have better performance.

2022-01-26 10:18 UTC, maxlig79 requested changes

2022-01-26 10:18 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +}
This is an int and you should return a bool

2022-01-26 10:20 UTC, maxlig79 requested changes

2022-01-26 10:20 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +        return NULL;
The return type is a string, NULL is a macro( zero )

2022-01-27 11:49 UTC, maxlig79 requested changes

2022-01-27 11:49 UTC, maxlig79 commented on herciuana_Task2/DynamicStringArray.cpp
> +    if (r == true)
Is not easier to return r?
Also this method is incomplete, doesn't delete the entry(string) in the case that is found.

2022-01-27 11:49 UTC, maxlig79 commented on herciuana_Task2/test.cpp
> +{
Please add also a test for the move assignment operator

2022-01-27 11:49 UTC, maxlig79 commented on herciuana_Task2/test.cpp
> +    BOOST_CHECK(array3.get_Size() == 3);
This test is wrong, the size sould be 2.

2022-01-27 16:54 UTC, maxlig79 submitted a review, later dismissed

2022-01-27 16:56 UTC, silvanadomnica approved these changes, later dismissed

2022-01-27 17:12 UTC, maxlig79 approved these changes

2022-01-27 17:13 UTC, silvanadomnica approved these changes

2022-01-27 17:13 UTC, merged