Implement server & client
maxlig79/accademy pull request #24
Opened 2022-01-28 12:52 UTC by ArdeleanuStefan

2022-01-28 17:36 UTC, maxlig79 requested changes

2022-01-28 17:36 UTC, maxlig79 commented on ArdeleanuStefan_Task3/client.cpp
> +      auto &cond = *m_managed_smh->find_or_construct<interprocess_condition>("cond")();
Maybe you should add in common.h consts for mutex and condition with better names than "mutex" and "condition".

2022-01-28 17:36 UTC, maxlig79 commented on ArdeleanuStefan_Task3/server.cpp
> +      auto &cond = *m_managed_smh->find_or_construct<interprocess_condition>("cond")();
Maybe you should add in common.h consts for mutex and condition with better names than "mutex" and "condition".

2022-01-28 17:36 UTC, maxlig79 commented on ArdeleanuStefan_Task3/server.cpp
> +{
The shared from the client is different than the shared from the server? If not maybe the namespace can be put in a common header.

2022-01-28 17:36 UTC, maxlig79 commented on ArdeleanuStefan_Task3/client.cpp
> +
You forgot to destroy the shared memory for ADD.

2022-01-28 17:36 UTC, maxlig79 commented on ArdeleanuStefan_Task3/server.cpp
> +   {
In this method there is a lot of common code, maybe you should consider to use inheritance and write only one external function.

2022-01-31 13:15 UTC, maxlig79 requested changes

2022-01-31 13:15 UTC, maxlig79 commented on ArdeleanuStefan_Task3/client.cpp
> +
Instead of "HELP" you should use the macro HELP_COMMAND.c_str()

2022-02-02 15:16 UTC, maxlig79 approved these changes

2022-02-02 15:18 UTC, MariaCraciun1 approved these changes

2022-02-02 15:19 UTC, merged