Implement communication
maxlig79/accademy pull request #25
Opened 2022-02-02 14:31 UTC by silvanadomnica

2022-02-02 14:43 UTC, maxlig79 requested changes

2022-02-02 14:43 UTC, maxlig79 commented on silvanadomnica_Task3/server.cpp
> +    stringShared *s =managed_sm.find_or_construct<stringShared>(ADD_COMMAND.c_str())("Add OK",managed_sm.get_segment_manager());
Here you should implement a switch in order to know what command to implement.

2022-02-02 14:43 UTC, maxlig79 commented on silvanadomnica_Task3/server.cpp
> +    stringShared *s =managed_sm.find_or_construct<stringShared>(ADD_COMMAND.c_str())("Add OK",managed_sm.get_segment_manager());
You should also add the functionality, addEntry, deleteEntry, etc.

2022-02-02 14:43 UTC, maxlig79 commented on silvanadomnica_Task3/client.cpp
> +      std::this_thread::sleep_for(std::chrono::milliseconds(100));
You should add a switch in order to know what response to expect: from add, delete, etc.

2022-02-04 13:06 UTC, maxlig79 submitted a review, later dismissed

2022-02-07 08:03 UTC, nbiro approved these changes, later dismissed

2022-02-07 09:09 UTC, vlcristi91 approved these changes

2022-02-07 09:43 UTC, maxlig79 approved these changes

2022-02-07 09:44 UTC, merged