Add Comunication Server Client
maxlig79/accademy pull request #27
Opened 2022-02-03 11:13 UTC by herciuana

Add Comunication Server Client

2022-02-03 11:20 UTC, maxlig79 requested changes

2022-02-03 11:20 UTC, maxlig79 commented on herciuana_Task3/client.cpp
> +      mq.send(&MQR, MAX_MESSAGE_SIZE, 0);
After the send you will need to wait for the server to process the command and add the result string into the shared memory.
You can use a condition wait here and in the server a condition notify.

2022-02-03 11:20 UTC, maxlig79 commented on herciuana_Task3/client.cpp
> +      std::pair<string *, std::size_t> ret = msm.find<string>(ADD_COMMAND.c_str());
You will have to check the command type (add, del, get) and perform the action for each command.

2022-02-07 07:07 UTC, maxlig79 approved these changes

2022-02-07 08:05 UTC, nbiro approved these changes

2022-02-07 09:08 UTC, vlcristi91 approved these changes

2022-02-07 09:40 UTC, merged