Multiple Client support
maxlig79/accademy pull request #37
Opened 2022-02-09 12:18 UTC by vlad-iancu

2022-02-09 13:15 UTC, maxlig79 requested changes

2022-02-09 13:15 UTC, maxlig79 commented on vlad_task3/src/ServerProxyObject.cpp
>          while (active)
Unfortunately the exit is not correct implemented: if one client send the exit command also the server will exit.

2022-02-09 13:15 UTC, maxlig79 commented on vlad_task3/include/Common.hpp
> +        ID = 6
You have added a command for this task, looks a little complicated.

2022-02-09 13:15 UTC, maxlig79 commented on vlad_task3/main_server.cpp
> +    server::ServerProxyObject serv(5);
What is 5 represents? Maybe you should use a macro or const.

2022-02-09 13:15 UTC, maxlig79 commented on vlad_task3/src/ClientProxyObject.cpp
> +    timeout(boost::posix_time::millisec(10))
Where is this timeout used?

2022-02-09 13:15 UTC, maxlig79 commented on vlad_task3/src/ClientProxyObject.cpp
> +        int clientId = getId();
Basically here the client is waiting for an id from the server which is pretty complicated.
Wouldn't be easier to add the client id to the send command(please check the other colleague work)?

2022-02-09 16:23 UTC, maxlig79 approved these changes

2022-02-10 06:29 UTC, MariaCraciun1 approved these changes

2022-02-10 07:13 UTC, maxlig79 approved these changes

2022-02-10 07:24 UTC, maxlig79 approved these changes

2022-02-10 07:25 UTC, merged