Files for task 2
maxlig79/accademy pull request #44
Opened 2022-02-11 13:06 UTC by bogdann98

2022-02-11 14:27 UTC, maxlig79 requested changes

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +    int i;
Why the is outside the for?

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +        int i;
Why the is outside the for?

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +            return "False";
If False is among the strings?

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +        int i;
Why i is outside the for?

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/TestDynamicStringArray.cpp
> +    if(array6.getSize() != array7.getSize())//Test for copy constructor
This is a test for asignment operator not copy constructor and is pretty strange because the array7 is empty.

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/TestDynamicStringArray.cpp
> +    BOOST_CHECK(array1.getSize()==array2.getSize()); //Test for overload
You already have a test like this.

2022-02-11 14:27 UTC, maxlig79 commented on bogdann98_task2/TestDynamicStringArray.cpp
> +    array2.addEntry("Romania");
This test is the same as test 1, you can test getentry for example

2022-02-11 15:09 UTC, nbiro commented on bogdann98_task2/DynamicStringArray.cpp
> +        }
indentation please, which block does this bracket close?

2022-02-14 10:26 UTC, maxlig79 approved these changes

2022-02-14 12:40 UTC, silvanadomnica approved these changes

2022-02-14 12:56 UTC, merged