Add move assignment operator
maxlig79/accademy pull request #47
Opened 2022-02-14 15:05 UTC by bogdann98

2022-02-14 16:56 UTC, maxlig79 requested changes

2022-02-14 16:56 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +    dynamicArray=new std::string[size];
This allocation has no sense, you already allocate memory in the addEntry.

2022-02-14 16:56 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.cpp
> +DynamicStringArray &DynamicStringArray::operator=(DynamicStringArray &&vec){
Please rename the variable vec

2022-02-14 16:56 UTC, maxlig79 commented on bogdann98_task2/DynamicStringArray.h
> +    DynamicStringArray(const vector<string> &vec);
You are missing the move operator

2022-02-15 10:35 UTC, maxlig79 approved these changes

2022-02-15 10:52 UTC, MariaCraciun1 approved these changes

2022-02-15 10:53 UTC, merged