Vlad ipc test
maxlig79/accademy pull request #52
Opened 2022-02-21 12:45 UTC by vlad-iancu

2022-02-21 14:09 UTC, maxlig79 submitted a review, later dismissed

2022-02-21 14:09 UTC, maxlig79 commented on vlad_task3/DynamicArrayProxyTest.cpp
> +    for (int i = 0; i < 100; i++)
This is not a parallel execution, maybe if you replace the for with for_each will work.

2022-02-21 14:09 UTC, maxlig79 commented on vlad_task3/DynamicArrayProxyTest.cpp
> +    for (int i = 0; i < 100; i++)
This is not a parallel execution, maybe if you replace the for with for_each will work.

2022-02-21 17:49 UTC, maxlig79 requested changes

2022-02-21 17:49 UTC, maxlig79 commented on vlad_task3/DynamicArrayProxyTest.cpp
> +        sscanf(line, fmt.c_str(), &idx, &client, &val);
If you don't use idx why bother?

2022-02-22 09:58 UTC, silvanadomnica approved these changes

2022-02-22 10:05 UTC, maxlig79 approved these changes

2022-02-22 10:05 UTC, merged