Ipc task for 1 client
maxlig79/accademy pull request #53
Opened 2022-02-22 14:48 UTC by bogdann98

2022-02-23 17:10 UTC, maxlig79 requested changes

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +            dynamicArray=new string[size -1];
Looks like a memory leak

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +            for(int j;j<size;j++)
What is j start value?

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +        if(found==1)
found is a bool, please use true and false.

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.h
> +    DynamicStringArray(DynamicStringArray &&obj);
I can't find the implementation of this constructor

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/server.cpp
> +        CommandPair commandPair=split_command(mqrstruct.command);
Please do something with the indentation...

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +    bool found = 0;
found is a bool or int?

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +        found = 1;
bool or int?

2022-02-23 17:10 UTC, maxlig79 commented on bogdann98_task3/DynamicStringArray.cpp
> +    if (dynamicArray[0] == String && size > 1)
So if the String is not found you will try anyway to modify the dynamicArray?
Can you please add a test where you delete a string that is not in the dynamicArray and see what happen.

2022-02-24 13:14 UTC, maxlig79 approved these changes

2022-02-24 19:12 UTC, silvanadomnica approved these changes

2022-02-25 07:01 UTC, merged