Implement Dynamic Array
maxlig79/accademy pull request #58
Opened 2022-03-01 11:45 UTC by ArdeleanuStefan

2022-03-02 11:28 UTC, maxlig79 requested changes

2022-03-02 11:28 UTC, maxlig79 commented on ArdeleanuStefan_Task5/include/DynamicArray.hpp
> +    {
Please implement the methods outside the class definition in order to separate the interface from the implementation.

2022-03-02 11:28 UTC, maxlig79 commented on ArdeleanuStefan_Task5/include/DynamicArray.hpp
> +        catch (const std::out_of_range &e)
I think you should catch the exceptions outside the method.
You also should specify that the method will throw an exception.

2022-03-02 11:28 UTC, maxlig79 commented on ArdeleanuStefan_Task5/include/DynamicArray.hpp
> +void DynamicArray<std::string>::addEntry(const std::string &input)
As an exercise you can try to implement this without specialization.

2022-03-04 11:53 UTC, maxlig79 approved these changes

2022-03-04 11:54 UTC, silvanadomnica approved these changes

2022-03-04 12:31 UTC, merged