Add template class dynamic array
maxlig79/accademy pull request #59
Opened 2022-03-02 07:39 UTC by silvanadomnica

2022-03-03 13:56 UTC, maxlig79 requested changes

2022-03-03 13:56 UTC, maxlig79 commented on silvanadomnica_Task5/DynamicStringArray.hpp
> +    catch (const std::out_of_range &e)
Please catch the exception in the boost test (you can use BOOST_CHECK_THROW)

2022-03-03 13:56 UTC, maxlig79 commented on silvanadomnica_Task5/DynamicStringArray.hpp
> +    catch (const std::invalid_argument &e)
Please catch the exception in the boost test (you can use BOOST_CHECK_THROW)

2022-03-04 11:19 UTC, maxlig79 approved these changes

2022-03-04 12:01 UTC, MariaCraciun1 approved these changes

2022-03-04 12:31 UTC, merged