DynamicArray class template
maxlig79/accademy pull request #61
Opened 2022-03-03 07:45 UTC by MariaCraciun1

2022-03-03 13:54 UTC, maxlig79 requested changes

2022-03-03 13:54 UTC, maxlig79 commented on MariaCraciun1_Task5/DynamicArray.hpp
> +    catch(const std::invalid_argument& e)
Please catch the exception in the boost test (you can use BOOST_CHECK_THROW)

2022-03-03 13:54 UTC, maxlig79 commented on MariaCraciun1_Task5/DynamicArray.hpp
> +    {
Please catch the exception in the boost test (you can use BOOST_CHECK_THROW)

2022-03-03 13:54 UTC, maxlig79 commented on MariaCraciun1_Task5/DynamicArray.hpp
> +{ return size; }
Indentation.

2022-03-07 06:39 UTC, maxlig79 approved these changes

2022-03-07 07:31 UTC, silvanadomnica approved these changes

2022-03-07 08:39 UTC, merged